### ISSUE TITLE
mittag-leffler package

### ISSUE THREAD

**Issue by PushkarevAS** [jdhuang-csm/hybrid-drt#1]
Dear Jake,

Could you please navigate to the specific mittag-leffler package, which is necessary for the hybrid-drt?

BR,
Artem Pushkarev

**Comment by jdhuang-csm** [comment]
Dear Artem,

The mittag-leffler package is available at https://github.com/jdhuang-csm/mittag-leffler. In the future, I will most likely incorporate the mittag-leffler package as a module in hybrid-drt to remove this dependency and make installation easier.
